version: '3'
services:
  bot:
    build: .
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OPENAI_KEY=${OPENAI_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  redis-data: